version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    networks:
      - default-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data    # Bind mount a la carpeta local
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - default-network


networks:
  default-network:
    driver: bridge
